Update linux workflow for testing

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -2,12 +2,69 @@ name: linux
 
 on: 
   push:
+    branches: [main] # NB: Runs whenever a PR is merged to main
   pull_request:
+    branches: [main] # NB: Runs when a PR to main is opened. This can be expanded to run when PRs are opened to other branches (i.e., testing-juce8)
+  release:
+    types: [published] # NB: Runs whenever a new release is created. Releases are based on tags, but are separate in that a tag can be created without a concurrent release
 
 jobs:
 
+  check-semver:
+    runs-on: ubuntu-22.04
+    if: github.event_name != 'release'
+    steps:
+      - name: Checkout current version
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Find previous release
+        id: previous-release
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          echo "RELEASE_NAME=$(gh release list -L 1 --json tagName -q .[0].tagName)" >> $GITHUB_OUTPUT
+          
+      - name: Checkout last release version
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ steps.previous-release.outputs.RELEASE_NAME }}
+          path: last-release
+          sparse-checkout: |
+            Source/OpenEphysLib.cpp
+          sparse-checkout-cone-mode: false
+
+      - name: Extract Versions
+        id: extract-versions
+        run: |
+          echo "CURRENT_VERSION=$(cat ./Source/OpenEphysLib.cpp | grep -w -e 'info->libVersion' | grep -Eo "[0-9]+.[0-9]+.[0-9]+" >> $GITHUB_OUTPUT
+          echo "PREVIOUS_VERSION=$(cat ./last-release/Source/OpenEphysLib.cpp | grep -w -e 'info->libVersion' | grep -Eo "[0-9]+.[0-9]+.[0-9]+" >> $GITHUB_OUTPUT
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.10.12"
+
+      - name: Install semver
+        run: python -m pip install semver
+
+      - name: Compare Versions
+        run: |
+         version_current=${{ steps.extract-versions.outputs.CURRENT_VERSION }}
+         version_release=${{ steps.extract-versions.outputs.PREVIOUS_VERSION }}
+ 
+         echo "Current Version: $version_current"
+         echo "Release Version: $version_release"
+         
+         if [ ! $(python -c "import semver; print(semver.compare(\"$version_current\", \"$version_release\"))") == 1 ]; then
+           echo "::error title=Invalid version number::Version number must be increased"
+           exit 1
+         fi
+
   build-linux:
 
+    needs: [check-semver]
+    if: always() && !failure() && !cancelled()
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -15,6 +72,7 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+
     - name: setup
       run: |
         sudo apt update
@@ -22,13 +80,29 @@ jobs:
         git clone https://github.com/open-ephys/plugin-GUI.git --branch testing-juce8
         sudo ./plugin-GUI/Resources/Scripts/install_linux_dependencies.sh
         cd plugin-GUI/Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
+    
     - name: build
+      id: build
       run: |
         cd Build
         cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
         make
-#    - name: test
-#      run: cd build && ctest
+        
+    - name: Collect packages
+      uses: actions/upload-artifact@v4
+      if: steps.build.outcome == 'success' && always()
+      with:
+        name: Build
+        if-no-files-found: error
+        path: Build/**
+
+  deploy-linux:
+
+    needs: [build-linux]
+    runs-on: ubuntu-22.04
+    if: github.event_name == 'release' && always() && !failure() && !cancelled()
+
+    steps:
     - name: deploy
       if: github.ref == 'refs/heads/main'
       env:
